project_id = "ijtpdrsoddgjwyeiqalg"

[functions.apply-referral]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.fetch-trending-topics]
verify_jwt = false

[functions.materialize-trending]
verify_jwt = false